.\" $Id$
.TH HDFLS 1 "July 1995" "NCSA HDF 4.0"
.SH NAME
hdfls \- List the content of an HDF file
.SH SYNOPSIS
.B hdfls
[
.B \-d
]
[
.B \-l
]
[
.B \-o
]
[
.B \-t
.I tag
]
[
.B \-v
]
.I filename
\&.\|.\|.
.SH DESCRIPTION
.B hdfls
lists the content of each
.I filename.
.SH OPTIONS
.TP
.B \-d
Shows the offset and length information of each element in the file.
.TP
.B \-o
Orders the elements by reference numbers.
.TP
.B \-l
Displays the elements in the long format with more information.
.TP
.B \-v
Using the verbose format to display the text of annotations and labels.
(Verbose format implies the long format).
.TP
.B \-t
.I tag
Lists only information about a specific type of
.I tag.
For example, 'hdfls \-t 700 foo.hdf'
lists information about Scientific Data Groups only.
.TP
.B \-s
Gives detailed descriptions of \fIspecial elements\fP.
.TP
.B \-g
Lists elements in groups.
.SH SEE ALSO
.BR hdf (1)
