.\" $Id$
.TH HDFPACK 1 "July 1995" "NCSA HDF 4.0"
.SH NAME
hdfpack \- Compact an HDF file
.SH SYNOPSIS
.B hdfpack
[
.B \-i
\||
.B \-b
]
[
.BI \-d n
]
[
.BI \-t n
]
[
.B \-x
]
[
.B \-r
.I from
.I to
]
.I infile
.I outfile
.SH DESCRIPTION
.B hdfpack
compacts an HDF file by reading in all the data elements in the file
and writing them out to a new file.
.SH OPTIONS
.TP
.B \-b
Don't coalesce linked-block elements.
Only one of options b and i can be specified.
.TP
.B \-i
Interactive mode; prompt for each linked-block element.
Only one of options b and i can be specified.
.TP
.BI \-d n
Force the output file to have 
.I n
DDs per DD block.
.TP
.BI \-t n
Force output file to have 
.I n
linked blocks per table entry.
.TP
.B \-x
Keep external objects external.
.TP
.BI \-r " from to "
Rename external object with external filename
.I from
to the filename
.I to.
.SH SEE ALSO
.BR hdf (1)
