.TH ristosds 1
.SH NAME
ristosds \- convert 2D raster images into a 3D Scientific Data Set.
.SH SYNOPSIS
.B ristosds
infilelist -o outfile
.SH DESCRIPTION
.I Ristosds
converts one or more 2D raster images into a 3D floating point
data set, and stores the data set into an HDF file.
.br 
.SH REQUIRED ARGUMENTS
.br
.TP 8
.B infilelist
A list of input HDF file names seperated by spaces. There should be
at least one file in the list. Each file contains one or more images.  
All the images must have the same sizes of dimensions. If there is
a palette associated with the images, the palette should be included in the first input file.
.TP
.B -o outfile
The name of output file which the 3D floating data set is to be stored in.
.SH OPTIONS
.SH
.SH SEE ALSO
.SH
.SH BUGS
Mail to sxu@ncsa.uiuc.edu

