.\" $Id$
.TH SDISDIMVAL_BWCOMP 3 "November 1995" "NCSA HDF 4.0"
.ft B
#include <mfhdf.h>
.TP
intn SDisdimval_bwcomp(int32 dimid)
.sp
.I  dimid
	IN: dimension ID returned from SDgetdimid
.TP
Purpose
.br
Get the backward compatibility of a dimension record.
.TP
Return value
Returns SD_DIMVAL_BW_COMP (1) if backward compatible, 
SD_DIMVAL_BW_INCOMP (0) if incompatible, FAIL if error.

.TP
Description
SDisdimval_bwcomp gets the backward compatibility of a dimension record.
SDstart reads dimension records into memory. The backward compatiblity 
of each dimesion is decided by the existance of the dimension 
vdata of class "DimVal0.0" in the dimension vgroup for that dimension. 
If "DimVal0.0" vdata doesn't exist in that dimension vgroup,
it will be flagged as backwards incompatible. The compatibility
can be changed by SDsetdimval_comp() any time between SDstart and
SDend. 

Unlimited dimension is always backward compatible.

.TP
Examples

.nf
status = SDisdimval_bwcomp(dimid1);
if (status == SD_DIMVAL_BW_COMP)  
    status = SDsetdimval_comp(dimid, SD_DIMVAL_BW_INCOMP);
.fi

.TP
FORTRAN 
integer function sfisdmvc(sdsid)
.br
integer sdsid
.br

.TP
See Also
SDsetdimval_comp(3)
