.\" $Id$
.TH "SDSETACCESSTYPE" 3 "July 1995" "NCSA HDF 4.0"
.TP
SDsetaccesstype (sfacct)
.TP
intn SDsetaccesstype(int32 sds_id, int32 accesstype) 

.I sds_id
	IN: The dataset ID returned from SDselect 
.br
.I accesstype
	IN: The type of I/O access for the dataset.

.TP
Purpose 
.br
Set the I/O access type for the dataset. 
.TP
Return value 
   Returns SUCCEED if successful and FAIL otherwise. 
.TP
Description 
.B SDsetaccesstype
sets the I/O access type for the dataset
.I sds_id to
.I accesstype.
The dataset must be an external element and the I/O access
applies to the related external file only.
.I accesstype
can be 
.B DFACC_SERIAL
for sequential I/O
or
.B DFACC_PARALLEL
for parallel I/O.
HDF has only implemented the
CM5 CMFS parallel I/O.

Though access type is set for dataset
.I sds_id,
it applies to the whole external file in which
the dataset resides. If different access types are set on datasets of the same 
HDF external file, unpredictable effects will result. It is also the users'
responsibility to make sure the access type is appropriate for the files
involved. For example, setting DFACC_PARALLEL on a dataset contained
in a serial file may result in slower I/O rates and sometimes failures.

.TP
FORTRAN 
integer function sfacct(sds_id, accesstype) 
.br
integer*4 sds_id, accesstype 
