.\" $Id$
.TH VSSETEXTERNALFILE 3 "Feburary 1996" "NCSA HDF 4.0" 
.TP
int32 VSsetexternalfile(int 32 id, char *filename, int32 offset)
.sp
.I id
	IN: vdata ID
.sp
.I filename
	IN: name of external file
.sp
.I offset
	IN: offset in external file
.TP
Purpose
.br
store Vdata info in a separate file

.TP
Return value
Return SUCCEED if no error, else FAIL.

.TP
Description
Specify that the actual data for this Vdata be stored in a 
separate file (an "external file" in HDF terms).

Only the data (as in VSwrite()) will be stored externally.  
Attributes and such will still be in the main file.

IMPORTANT:  It is the user's responsibility to see that the 
separate files are transported with the main file.
.TP
FORTRAN
integer function vsfsextf(id, filename, offset)
.br
integer*4	id, offset
.br
character*(*)   filename

