# Makefile for ncgen(1).
#
# $Id$

PROGRAM		= ncgen
BINFILES	= $(PROGRAM)
CPP_NETCDF	= -I../libsrc
CPPFLAGS	= $(CPP_NETCDF) @CPPFLAGS@
CFLAGS		= @CFLAGS@ @HDF_INC@
FFLAGS		= @FFLAGS@
MANUALS		= ncgen.1
GARBAGE		= $(PROGRAM) \
		  ncgenyy.c ncgentab.c ncgentab.h \
		  test0.nc test1.nc test1.cdl test2.cdl test0.f ctest0 \
		  ftest0 ftest0.nc ftest1.cdl test0.c ctest0.nc ctest1.cdl
vms_stuff	= vmstab.c vmstab.h vms_yy.c
MANIFEST	= Makefile.in depend README \
		  close.c descrip.mms escapes.c generate.c generic.h \
		  genlib.c genlib.h getfill.c init.c lexyacc.com load.c \
		  main.c make.com msoft.mk msofttab.c msofttab.h \
		  msoftyy.c ncgen.1 ncgen.h ncgen.l ncgen.opt ncgen.y \
		  test.com test0.cdl \
		  $(vms_stuff)
LIBNAME		= netcdf
LD_NETCDF	= ../libsrc/libnetcdf.a @HDF_LIB@ @JPEG_LIB@
OBJS		= main.o generate.o load.o ncgentab.o escapes.o \
		  getfill.o init.o close.o genlib.o
LD_XDR		= @LD_XDR@
LIBS		= $(LD_NETCDF) $(LD_XDR)
LEX		= @LEX@
YACC		= @YACC@
prefix		= ../../..

all::		$(PROGRAM)

test:           $(PROGRAM) test0.cdl btest ctest ftest FORCE

install::	installed_program installed_manuals

$(PROGRAM):	main.o

ncgentab.c \
ncgentab.h:	ncgen.y ncgenyy.c ncgen.h
	$(YACC) -d ncgen.y
	mv y.tab.c ncgentab.c
	mv y.tab.h ncgentab.h

ncgenyy.c:	ncgen.l
	$(LEX) ncgen.l
	mv lex.yy.c ncgenyy.c

# The SunOS 4.1.3 yacc(1) doesn't generate correct code.
#
vms-stuff:	ncgentab.h ncgentab.c ncgenyy.c
	cp ncgentab.h vmstab.h
	cp ncgentab.c vmstab.c
	cp ncgenyy.c vms_yy.c

#
# test "-b" option of ncgen
#
btest:		$(PROGRAM) test0.cdl test1.cdl
	./$(PROGRAM) -b test1.cdl
	$(NCDUMP) test1.nc > test2.cdl
	@diff test1.cdl test2.cdl && \
	    echo "*** $(PROGRAM) -b test successful ***"

#
# test "-c" option of ncgen
#
ctest:		test1.cdl ctest0
	./ctest0		# tests `-c' option, creates ctest0.nc
	$(NCDUMP) -n test1 ctest0.nc > ctest1.cdl
	@diff test1.cdl ctest1.cdl && \
	    echo "*** $(PROGRAM) -c test successful ***"

ctest0:		ncgen test0.cdl
	./$(PROGRAM) -c -o ctest0.nc test0.cdl > test0.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ test0.c $(LIBS)

#
# test "-f" option of ncgen
#
ftest:		test1.cdl
	@case "$(FC)" in \
	NONE*) \
	    echo 1>&2 "\`$@' not made because no FORTRAN compiler";; \
	*) \
	    $(MAKE) $(MFLAGS) ftest0; \
	    ./ftest0 ; \
	    $(NCDUMP) -n test1 ftest0.nc > ftest1.cdl; \
	    if diff test1.cdl ftest1.cdl; then \
		echo "*** ncgen -f test successful ***"; \
	    else \
		echo "*** ncgen -f test failed " \
		    "(but roundoff differences are OK) ***"; \
	    fi;; \
	esac

ftest0:		$(PROGRAM) test0.cdl
	@case "$(FC)" in \
	NONE*) \
	    echo 1>&2 "\`$@' not made because no FORTRAN compiler";; \
	*) \
	    $(MAKE) $(MFLAGS) netcdf.inc; \
	    ./$(PROGRAM) -f -o ftest0.nc test0.cdl > test0.f; \
	    $(FC) $(FFLAGS) -o $@ test0.f $(LIBS);; \
	esac

test1.cdl:	test0.nc
	$(NCDUMP) -n test1 test0.nc > $@

test0.nc:	$(PROGRAM) test0.cdl
	./$(PROGRAM) -b -o test0.nc test0.cdl

netcdf.inc:
	@case "$(FC)" in \
	NONE*) \
	    echo 1>&2 "\`$@' not made because no FORTRAN compiler";; \
	*) \
	    ln -s ../fortran/$@ .;; \
	esac

include ../port/master.mk

# Override the default definition for ncdump(1) in the master makefile.
#
NCDUMP		= ../ncdump/ncdump

### Everything after the following line might be overwritten ###
### DO NOT DELETE THIS LINE.  make depend DEPENDS ON IT ###
include depend
