#
# $Header$
#
# $Log$
# Revision 1.2  1992/03/24 20:40:09  sxu
# Bugs fixed in lib and include directories
#
# Revision 1.1  1992/03/01  23:39:01  mfolk
# Initial revision
#
#

# ##################################################################
#
#                   NCSA HDF Version 3.2 release Beta 1
#                               March 1992
#                  MAKEFILE for testing HDF Version 3.2
#
#                          ABOUT THIS MAKEFILE
#
# This makefile creates HDF test programs.  There are three categories
# of test programs: 
#
#              application layer C test programs 
#              application layer FORTRAN test programs 
#              lower level C test programs 
#
# The application layer C test programs are:
#
#              tdfr8     (8-bit raster image sets)
#              tdf24     (24-bit raster image sets)
#              tdfp      (palettes)
#              tdfsd_nt  (scientific data sets, data only)
#              tdfsd_mms (scientific data sets, data, max/min and scales)
#              tdfan     (annotations for HDF objects)
#              tdfanfile (annotations for HDF files)
#              tdfstubs  (emulation of old lower level i/o routines)
#
# The application layer FORTRAN test programs are:
#
#              tdfsd_ntF  (scientific data sets, data only)
#              tdfsd_mmsF (scientific data sets, data, max/min and scales)
#
# The lower level C test programs are:
#
#              thfile     (basic i/o)
#              terr       (error handling)
#              thblocks   (linked blocks)
#              thextelt   (i/o involving external files)
#              tvers      (storing and retrieving version strings)
#              thlinkage  (linkage of functions)
#
# ##################################################################
#
#                      HOW TO USE THIS MAKEFILE
#
# You need libdf.a to compile any of these test programs.  You will
# also need selected header files as described below.
#
# To compile the application layer C test programs, enter "make ctests".  
# If there are test programs that you do not want to compile, do this 
# by removing them from the lines "COBJS=" and "CSRCS=" below.
# You need access to the header files indicated in the "CHDRS=" line
# below to compile these programs. 
#
# To compile the application layer FORTRAN test programs, enter 
# "make ftests".  You need access to the header files indicated in 
# the "FHDRS=" line below to compile these programs. 
# If there are test programs that you do not want to compile, do this 
# by removing them from the lines "FOBJS=" and "FSRCS=" below.
#
# To compile the lower level C test programs, enter "make htests". 
# You need access to the header files indicated in the "HHDRS=" line
# below to compile these programs.  If there are test programs that 
# you do not want to compile, do this by removing them from the lines 
# "HOBJS=" and "HSRCS=" below.
#
# To remove all object files created by this makefile, enter "make clean"
#
# To remove ALL files created by this makefile, enter "make cleanup"
#
# ##################################################################
#
#                       PORTING INSTRUCTIONS
#
# You must modify the lines containing the symbol "==>" to make
# this makefile compatible with your platform.
#
# ##################################################################

# ==> specify your machine
MACHINE=SUN

# ==> specify your fortran compiler
FC=f77 -g
FFLAGS=

# ==> specify your C compiler
CC=cc
CFLAGS=  -g -D${MACHINE} $(IFLAGS)

# ==> where are your hdf.h, hdfi.h and vg.h files located?
IFLAGS=   -I/hdf/home/sxu/3.2tar/include -I.

# ==> where is your HDF library (libdf.a) located?
LIBS= /hdf/home/sxu/3.2tar/lib/libdf.a

RM=/bin/rm
RMFLAGS=-f

CTESTS= tdfr8 tdf24 tdfsd_mms tdfsd_nt tdfan tdfanfile tdfp tdfstubs 
CHDRS = df.h dfi.h dfsd.h vg.h df.h dfi.h dfstubs.h
CTSRCS= tdfr8.c tdf24.c tdfsd_mms.c tdfsd_nt.c tdfan.c tdfanfile.c \
        tdfp.c tdfstubs.c 
CTOBJS= tdfr8.o tdf24.o tdfsd_mms.o tdfsd_nt.o tdfan.o tdfanfile.o \
        tdfp.o tdfstubs.o 

HTESTS= thfile thfile1 terr thblocks thextelt 
HHDRS = hfile.h hdf.h hdfi.h herr.h hproto.h 
HTSRCS= thfile.c thfile1.c terr.c thblocks.c thextelt.c 
HTOBJS= thfile.o thfile1.o terr.o thblocks.o thextelt.o

FTESTS= tdfsd_ntF
FSRCS = tdfsd_mmsF.c tdfsd_ntF.c
FOBJS = tdfsd_mmsF.o tdfsd_ntF.o

all: ctests ftests htests

ctests: $(CTESTS)

ftests: $(FTESTS)

htests: $(HTESTS)
	
tdfr8:  tdfr8.c 
	$(CC) $(CFLAGS) -D$(MACHINE) tdfr8.c $(LIBS) -o tdfr8

tdf24:  tdf24.c 
	$(CC) $(CFLAGS) -D$(MACHINE) tdf24.c $(LIBS) -o tdf24

tdfp:   tdfp.c 
	$(CC) $(CFLAGS) -D$(MACHINE) tdfp.c $(LIBS) -o tdfp

tdfsd_nt:    tdfsd_nt.c 
	$(CC) $(CFLAGS) -D$(MACHINE) tdfsd_nt.c $(LIBS) -o tdfsd_nt

tdfsd_mms:    tdfsd_mms.c 
	$(CC) $(CFLAGS) -D$(MACHINE) tdfsd_mms.c $(LIBS) -o tdfsd_mms

tdfan:  tdfan.c 
	$(CC) $(CFLAGS) -D$(MACHINE) tdfan.c $(LIBS) -o tdfan

tdfanfile:     tdfan.c 
	$(CC) $(CFLAGS) -D$(MACHINE) tdfanfile.c $(LIBS) -o tdfanfile

tdfstubs:     tdfstubs.c 
	$(CC) $(CFLAGS) -D$(MACHINE) tdfstubs.c $(LIBS) -o tdfstubs

tdfsd_ntF:   tdfsd_ntF.f
	$(FC) $(FFLAGS) tdfsd_ntF.f $(LIBS)  -o tdfsd_ntF 

#tdfsd_mmsF:   tdfsd_mmsF.f 
#	$(FC) $(FFLAGS) tdfsd_mmsF.f $(LIBS) -o tdfsd_mmsF

thfile:     thfile.c 
	$(CC) $(CFLAGS) -D$(MACHINE) thfile.c $(LIBS) -o thfile

thfile1:     thfile1.c 
	$(CC) $(CFLAGS) -D$(MACHINE) thfile1.c $(LIBS) -o thfile1

terr:     terr.c 
	$(CC) $(CFLAGS) -D$(MACHINE) terr.c $(LIBS) -o terr

thblocks:     thblocks.c 
	$(CC) $(CFLAGS) -D$(MACHINE) thblocks.c $(LIBS) -o thblocks

thextelt:     thextelt.c
	$(CC) $(CFLAGS) -D$(MACHINE) thextelt.c $(LIBS) -o thextelt


