SET (CTEST_CUSTOM_MAXIMUM_NUMBER_OF_WARNINGS 1500)

SET (CTEST_CUSTOM_WARNING_EXCEPTION
    ${CTEST_CUSTOM_WARNING_EXCEPTION}
    "SZIP.src.*:[ \t]*warning"
    "jpeg.src.*:[ \t]*warning"
    "POSIX name for this item is deprecated"
    "disabling jobserver mode"
)
 
 
SET (CTEST_CUSTOM_MEMCHECK_IGNORE
    ${CTEST_CUSTOM_MEMCHECK_IGNORE}
    hdfpack-clear-refs
    hdfpalette-clear-refs
    hdfjpeg-clear-refs
    HDP_tst-clearall-objects
    HDP_tst_err-clearall-objects
    HDP-clear-my.dat
    HDP-clear-mybin.dat
    hdfimport-clear-refs
    HDIFF-clearall-objects
    hrepack-clearall-objects
    HDF_FORTRAN_EXAMPLES-clearall-objects
    MFHDF_EXAMPLES-clearall-objects
    MFHDF_TEST-clearall-objects
    testhdf-clearall-objects
    testhdf_thf0-clearall-objects
    testhdf_thf1-clearall-objects
    testhdf_thf2-clearall-objects
    testhdf_thf3-clearall-objects
    testhdf_thf4-clearall-objects
    testhdf_thf5-clearall-objects
    testhdf_thf6-clearall-objects
    testhdf_thf7-clearall-objects
    testhdf_thf8-clearall-objects
    testhdf_thf9-clearall-objects
    testhdf_thf10-clearall-objects
    testhdf_thf11-clearall-objects
    testhdf_thf12-clearall-objects
    testhdf_thf13-clearall-objects
    testhdf_thf14-clearall-objects
    testhdf_thf15-clearall-objects
    testhdf_thf16-clearall-objects
    testhdf_thf17-clearall-objects
    testhdf_thf18-clearall-objects
    testhdf_thf19-clearall-objects
    testhdf_thf20-clearall-objects
    testhdf_thf21-clearall-objects
    testhdf_thf22-clearall-objects
    testhdf_thf23-clearall-objects
    testhdf_thf24-clearall-objects
    testhdf_thf25-clearall-objects
    testhdf_thf26-clearall-objects
    testhdf_thf27-clearall-objects
    testhdf_thf28-clearall-objects
    testhdf_thf29-clearall-objects
    testhdf_thf30-clearall-objects
    testhdf_thf31-clearall-objects
    testhdf_thf32-clearall-objects
    testhdf_thf33-clearall-objects
    testhdf_thf34-clearall-objects
    testhdf_thf35-clearall-objects
    testhdf_thf36-clearall-objects
    testhdf_thf37-clearall-objects
    testhdf_thf38-clearall-objects
    testhdf_thf39-clearall-objects
    testhdf_thf40-clearall-objects
    testhdf_thf41-clearall-objects
    testhdf_thf42-clearall-objects
    testhdf_thf43-clearall-objects
    testhdf_thf44-clearall-objects
    testhdf_thf45-clearall-objects
    testhdf_thf46-clearall-objects
    testhdf_thf47-clearall-objects
    testhdf_thf48-clearall-objects
    testhdf_thf49-clearall-objects
    testhdf_thf50-clearall-objects
    testhdf_thf51-clearall-objects
    testhdf_thf52-clearall-objects
    testhdf_thf53-clearall-objects
    testhdf_thf54-clearall-objects
    testhdf_thf55-clearall-objects
    testhdf_thf56-clearall-objects
    testhdf_thf57-clearall-objects
    testhdf_thf58-clearall-objects
    testhdf_thf59-clearall-objects
    testhdf_thf60-clearall-objects
    hrepack-clearall-objects
    MFHDF_FORTRAN-clearall-objects
    HDF_FORTRAN-clearall-objects
    hdfgif-clear-refs
    ncdump-clearall-objects
    NC_TEST-clearall-objects                            
    HEDIT-hdfed.input1
    HEDIT-ristosds.input1
    HDFLS_NOL-test.hdf
    HDFLS_NOL-test.pck
    palettecomp
    HDFLS-storm.hdf
    storm110comp
    storm120comp
    storm130comp
    storm140comp
    HDFLS-allstorms.hdf
    HDFLS-allcomp.hdf
    HDFLS-jpeg.hdf
    jpeg2comp
    HDP-list-1
    HDP-list-2
    HDP-list-3
    HDP-list-4
    HDP-list-5
    HDP-list-6
    HDP-list-7
    HDP-list-8
    HDP-list-9
    HDP-list-10
    HDP-dumpsds-1
    HDP-dumpsds-2
    HDP-dumpsds-3
    HDP-dumpsds-4
    HDP-dumpsds-5
    HDP-dumpsds-6
    HDP-dumpsds-7
    HDP-dumpsds-8
    HDP-dumpsds-9
    HDP-dumpsds-10
    HDP-dumpsds-11
    HDP-dumpsds-13
    HDP-dumpsds-14
    HDP-dumpsds-15szip
    HDP-dumpsds-16
    HDP-dumpsds-17
    HDP-dumprig-1
    HDP-dumprig-2
    HDP-dumprig-3
    HDP-dumprig-4
    HDP-dumprig-5
    HDP-dumprig-6
    HDP-dumpvd-1
    HDP-dumpvd-2
    HDP-dumpvd-3
    HDP-dumpvd-4
    HDP-dumpvd-5
    HDP-dumpvd-6
    HDP-dumpvd-7
    HDP-dumpvd-8
    HDP-dumpvd-9
    HDP-dumpvd-10
    HDP-dumpvd-11
    HDP-dumpvd-12
    HDP-dumpvg-1
    HDP-dumpvg-2
    HDP-dumpvg-3
    HDP-dumpvg-4
    HDP-dumpvg-5
    HDP-dumpvg-6
    HDP-dumpvg-7
    HDP-dumpvg-8
    HDP-dumpvg-9
    HDP-dumpvg-10
    HDP-dumpvg-11
    HDP-dumpvg-12
    HDP-dumpvg-13
    HDP-dumpvg-14
    HDP-dumpvg-15
    HDP-dumpgr-1
    HDP-dumpgr-2
    HDP-dumpgr-3
    HDP-dumpgr-4
    HDP-dumpgr-5
    HDP-dumpgr-6
    HDP-dumpgr-7
    HDP-dumpgr-8
    HDP-dumpgr-9
    HDP-dumpgr-10
    HDP-dumpgr-11
    HDP-dumpgr-12
    HDP-dumpgr-13
    HDP-dumpgr-14
    HDP-dumpgr-15
    HDP-dumpgr-16
    HDP-dumpgr-17
    HDP-dumpgr-18
    HDP-dumpgr-19
    HIMPORTLS-ctxtr2
    HIMPORTLS-ctxtr3
    HIMPORTLS-cb32i2
    HIMPORTLS-cb32i3
    HIMPORTLS-cb16i2
    HIMPORTLS-cb16i3
    HIMPORTLS-cb32r2
    HIMPORTLS-cb32r3
    HIMPORTLS-cb64r2
    HIMPORTLS-cb64r3
    HIMPORTLS-cb64r2-n
    HIMPORTLS-cb64r3-n
    HIMPORTLS-ctxtr2_ris
    HIMPORTLS-cb64r2_ris
    HDIFF-hdiff_01
    HDIFF-hdiff_02
    HDIFF-hdiff_03
    HDIFF-hdiff_04
    HDIFF-hdiff_05
    HDIFF-hdiff_06
    HDIFF-hdiff_07
    HDIFF-hdiff_08
    HDIFF-hdiff_09
    HDIFF-hdiff_10
    HDIFF-hdiff_11
    HDIFF-hdiff_12
    HDIFF-hdiff_13
    HDIFF-hdiff_14
    HDIFF-hdiff_15
)