@startgantt

title HDF4 Release Schedule

projectscale monthly
Project starts 2023-01-01

[4.2] starts 2022-01-01 and lasts 61 weeks
[4.2.16] happens 2023-02-28
[4.2.16-2] happens 2023-06-30
[4.2.16-2] displays on same row as [4.2.16]
[4.2] is colored in #2EDB54

[4.3] starts 2024-02-28 and lasts 44 weeks
[4.3.0] happens 2024-02-28
[4.3] is colored in #3385FF

@endgantt
