name: hdf4 CMake aocc

on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string

permissions:
  contents: read

jobs:
  aocc_build_and_test:
    name: "aocc ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install Linux dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install ninja-build doxygen graphviz
          sudo apt install libssl3 libssl-dev libcurl4 libcurl4-openssl-dev
          sudo apt install -y libaec-dev zlib1g-dev wget curl bzip2 flex bison cmake libzip-dev openssl build-essential

      - name: Install AOCC 4.1.0
        run: |
          wget https://download.amd.com/developer/eula/aocc/aocc-4-1/aocc-compiler-4.1.0.tar
          tar -xvf aocc-compiler-4.1.0.tar
          cd aocc-compiler-4.1.0
          bash install.sh
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          which clang
          which flang
          clang -v
          echo "CC=/home/runner/work/hdf4/hdf4/aocc-compiler-4.1.0/bin/clang" >> $GITHUB_ENV
          echo "FC=/home/runner/work/hdf4/hdf4/aocc-compiler-4.1.0/bin/flang" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/home/runner/work/hdf4/hdf4/aocc-compiler-4.1.0/lib:/usr/local/lib" >> $GITHUB_ENV
          echo "LD_RUN_PATH=/home/runner/work/hdf4/hdf4/aocc-compiler-4.1.0/lib:/usr/local/lib" >> $GITHUB_ENV
          echo "DESTDIR=/tmp" >> $GITHUB_ENV

      - name: CMake Configure with aocc
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          cmake -C $GITHUB_WORKSPACE/config/cmake/cacheinit.cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
          -DJPEG_USE_LOCALCONTENT=OFF \
          -DLIBAEC_USE_LOCALCONTENT=OFF \
          -DZLIB_USE_LOCALCONTENT=OFF \
          -DHDF4_BUILD_FORTRAN:BOOL=ON \
          -DHDF4_BUILD_JAVA:BOOL=OFF \
          $GITHUB_WORKSPACE

      # BUILD
      - name: CMake Build
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          cmake --build . --parallel 3 --config ${{ inputs.build_mode }}
        working-directory: ${{ runner.workspace }}/build

      # RUN TESTS
      - name: CMake Run Tests
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          ctest . --parallel 2 -C ${{ inputs.build_mode }} -V
        working-directory: ${{ runner.workspace }}/build
