name:  hdf4 autotools aocc

on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string

permissions:
  contents: read

jobs:
  aocc_build_and_test:
    name: "AOCC ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install System dependencies
        run: |
          sudo apt update
          sudo apt install -y libaec-dev zlib1g-dev automake autoconf libcurl4-openssl-dev libjpeg-dev wget curl bzip2 m4 flex bison cmake libzip-dev doxygen openssl libtool libtool-bin build-essential libncurses-dev libquadmath0 libstdc++6 libxml2

      - name: Install AOCC 4.1.0
        run: |
          wget https://download.amd.com/developer/eula/aocc/aocc-4-1/aocc-compiler-4.1.0.tar
          tar -xvf aocc-compiler-4.1.0.tar
          cd aocc-compiler-4.1.0
          bash install.sh
          source /home/runner/work/hdf5/hdf5/setenv_AOCC.sh
          which clang
          which flang
          clang -v

      - name: Autotools Configure
        shell: bash
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/hdf5/hdf5/aocc-compiler-4.1.0/lib:/usr/local/lib
          export LD_RUN_PATH=/home/runner/work/hdf5/hdf5/aocc-compiler-4.1.0/lib:/usr/local/lib
          sh ./autogen.sh
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          $GITHUB_WORKSPACE/configure \
            --enable-build-mode=${{ inputs.build_mode }} \
            --enable-netcdf \
            --enable-shared \
            --disable-fortran \
             LDFLAGS="-L/home/runner/work/hdf5/hdf5/aocc-compiler-4.1.0/lib 
             CC=/home/runner/work/hdf5/hdf5/aocc-compiler-4.1.0/bin/clang
             FC=/home/runner/work/hdf5/hdf5/aocc-compiler-4.1.0/bin/flang

      # BUILD
      - name: Autotools Build
        run: |
          export PATH=$PATH:/home/runner/work/hdf5/hdf5/aocc-compiler-4.1.0/bin
          make -j3
        working-directory: ${{ runner.workspace }}/build

      # RUN TESTS
      # NORMAL
      - name: Autotools Run Tests
        run: |
          export PATH=$PATH:/home/runner/work/hdf5/hdf5/aocc-compiler-4.1.0/bin
          make check -j2
        working-directory: ${{ runner.workspace }}/build

      # INSTALL (note that this runs even when we don't run the tests)
      - name: Autotools Install
        run: |
          export PATH=$PATH:/home/runner/work/hdf5/hdf5/aocc-compiler-4.1.0/bin
          make install
          make uninstall
