name: hdf4 autotools aocc

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string
      build_option:
        description: "--enable-production or --disable-production"
        required: true
        type: string

permissions:
  contents: read

jobs:
  aocc_build_and_test:
    name: "aocc ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v4.1.7

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libaec-dev zlib1g-dev automake autoconf libcurl4-openssl-dev
          sudo apt install -y libjpeg-dev wget curl bzip2 m4 flex bison cmake libzip-dev
          sudo apt install -y doxygen openssl libtool libtool-bin build-essential
          sudo apt install -y libquadmath0 libstdc++6 libxml2

      - name: Install AOCC 4.2.0
        shell: bash
        run: |
          wget https://download.amd.com/developer/eula/aocc/aocc-4-2/aocc-compiler-4.2.0.tar
          tar -xvf aocc-compiler-4.2.0.tar
          cd aocc-compiler-4.2.0
          bash install.sh
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          which clang
          which flang
          clang -v

      - name: Autotools Configure
        shell: bash
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/hdf4/hdf4/aocc-compiler-4.2.0/lib:/home/runner/work/hdf5/hdf5/openmpi-4.1.6-install/lib:/usr/local/lib
          export LD_RUN_PATH=/home/runner/work/hdf4/hdf4/aocc-compiler-4.2.0/lib:/home/runner/work/hdf5/hdf5/openmpi-4.1.6-install/lib:/usr/local/lib
          export PATH=/usr/local/bin:$PATH
          sh ./autogen.sh
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          $GITHUB_WORKSPACE/configure \
            ${{ inputs.build_option }} \
            --enable-shared \
            --disable-fortran \
            LDFLAGS="-L/home/runner/work/hdf4/hdf4/aocc-compiler-4.2.0/lib"

      - name: Autotools Build
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          make -j3
        working-directory: ${{ runner.workspace }}/build

      - name: Autotools Run Tests
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          make check -j2
        working-directory: ${{ runner.workspace }}/build

      - name: Autotools Install
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          make install
        working-directory: ${{ runner.workspace }}/build

  aocc_static_build_and_test:
    name: "aocc static ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v4.1.7

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libaec-dev zlib1g-dev automake autoconf libcurl4-openssl-dev
          sudo apt install -y libjpeg-dev wget curl bzip2 m4 flex bison libzip-dev doxygen openssl
          sudo apt install -y libtool libtool-bin build-essential libquadmath0 libstdc++6 libxml2

      - name: Install AOCC 4.2.0
        shell: bash
        run: |
          wget https://download.amd.com/developer/eula/aocc/aocc-4-2/aocc-compiler-4.2.0.tar
          tar -xvf aocc-compiler-4.2.0.tar
          cd aocc-compiler-4.2.0
          bash install.sh
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          which clang
          which flang
          clang -v

      - name: Autotools Configure
        shell: bash
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/hdf4/hdf4/aocc-compiler-4.2.0/lib:/home/runner/work/hdf5/hdf5/openmpi-4.1.6-install/lib:/usr/local/lib
          export LD_RUN_PATH=/home/runner/work/hdf4/hdf4/aocc-compiler-4.2.0/lib:/home/runner/work/hdf5/hdf5/openmpi-4.1.6-install/lib:/usr/local/lib
          export PATH=/usr/local/bin:$PATH
          sh ./autogen.sh
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          $GITHUB_WORKSPACE/configure \
            ${{ inputs.build_option }} \
            --disable-shared \
            --enable-fortran \
            LDFLAGS="-L/home/runner/work/hdf4/hdf4/aocc-compiler-4.2.0/lib"

      - name: Autotools Build
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          make -j3
        working-directory: ${{ runner.workspace }}/build

      - name: Autotools Run Tests
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          make check -j2
        working-directory: ${{ runner.workspace }}/build

      - name: Autotools Install
        shell: bash
        run: |
          source /home/runner/work/hdf4/hdf4/setenv_AOCC.sh
          export PATH=/usr/local/bin:$PATH
          make install
        working-directory: ${{ runner.workspace }}/build
