name: clang-format Check
on:
  workflow_dispatch:
  push:
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C and Java programs.
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        extensions: 'c,h,cpp,hpp,java'
        clangFormatVersion: 13
        inplace: True
        style: file
        exclude: './config ./mfhdf/ncgen/ncgenyy.c ./mfhdf/ncgen/ncgentab.c ./mfhdf/ncgen/ncgentab.h'
    - uses: EndBug/add-and-commit@v7
      with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Committing clang-format changes'
