name: hdf4 autotools cygwin

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string
      build_option:
        description: "--enable-production or --disable-production"
        required: true
        type: string

permissions:
  contents: read

jobs:
  cygwin_build_and_test:
    name: "cygwin ${{ inputs.build_mode }}"
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf input

      - name: Get Sources
        uses: actions/checkout@v4.1.7

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: automake make gcc-fortran jpeg libjpeg-devel libtool zlib-devel

      - name: Autotools Configure
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
        run: |
          export PATH=/usr/bin:$PATH
          sh ./autogen.sh
          mkdir build
          cd build
          ../configure \
            ${{ inputs.build_option }} \
            --enable-shared \
            --disable-fortran

      - name: Autotools Build
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
        run: |
          export PATH=/usr/bin:$PATH
          cd build
          make -j3

      - name: Autotools Run Tests
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
        run: |
          export PATH=/usr/bin:$PATH
          cd build
          make check -j

      - name: Autotools Install
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
        run: |
          export PATH=/usr/bin:$PATH
          cd build
          make install
