name: hdf4 CMake cygwin

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string

permissions:
  contents: read

jobs:
  cygwin_build_and_test:
    name: "cygwin-${{ inputs.build_mode }}"
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf input

      - name: Get Sources
        uses: actions/checkout@v4.1.7

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: cmake gcc-fortran libjpeg-devel make ninja zlib-devel

      - name: CMake Configure
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
        run: |
          export PATH=/usr/bin:$PATH
          mkdir build
          cd build
          cmake -C ../config/cmake/cacheinit.cmake \
            -G Ninja \
            --log-level=VERBOSE \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DBUILD_SHARED_LIBS:BOOL=OFF \
            -DJPEG_USE_LOCALCONTENT=OFF \
            -DLIBAEC_USE_LOCALCONTENT=OFF \
            -DZLIB_USE_LOCALCONTENT=OFF \
            -DHDF4_BUILD_FORTRAN:BOOL=ON \
            -DHDF4_BUILD_JAVA:BOOL=OFF \
            ..

      - name: CMake Build
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
        run: |
          export PATH=/usr/bin:$PATH
          cd build
          cmake --build . --parallel 3 --config ${{ inputs.build_mode }}

      - name: CMake Run Tests
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
        run: |
           export PATH=/usr/bin:$PATH
           cd build
           ctest . --parallel 2 -C ${{ inputs.build_mode }} -V
