name: cygwin

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.github/CODEOWNERS'
    - 'release_notes/**'
    - 'COPYING'
    - '**.md'

permissions:
  contents: read

# Using concurrency to cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cygwin-cmake:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf input

      - uses: actions/checkout@v4

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: cmake gcc-fortran libjpeg-devel make ninja zlib-devel
      - name: Test HDF4
        run: |
          export PATH=/usr/bin:$PATH
          mkdir build
          cd build
          which cmake
          cmake -G Ninja \
           -D BUILD_SHARED_LIBS:BOOL=OFF \
           ..
          cmake --build . --config Release          
          ctest . -C Release -V
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
