name: hdf4 dev daily build

# Triggers the workflow on a schedule or on demand
on:
  workflow_dispatch:
  schedule:
    - cron: "6 0 * * *"

permissions:
  contents: read

jobs:
  get-old-names:
    runs-on: ubuntu-latest
    outputs:
      hdf4-name: ${{ steps.gethdf4base.outputs.HDF4_NAME_BASE }}

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Get hdf4 release base name
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: 'tags/snapshot'
        file: 'last-file.txt'

    - name: Read base-name file
      id: gethdf4base
      run: echo "HDF4_NAME_BASE=$(cat last-file.txt)" >> $GITHUB_OUTPUT

    - run: echo "hdf4 base name is ${{ steps.gethdf4base.outputs.HDF4_NAME_BASE }}."

  call-workflow-tarball:
    uses: ./.github/workflows/tarball.yml
    with:
      use_tag: snapshot
      use_environ: snapshots

  call-workflow-ctest:
    needs: call-workflow-tarball
    uses: ./.github/workflows/cmake-ctest.yml
    with:
      preset_name: ci-StdShar
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
#      use_tag: snapshot
      use_environ: snapshots
    secrets:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
        AZURE_CODE_SIGNING_NAME: ${{ secrets.AZURE_CODE_SIGNING_NAME }}
        AZURE_CERT_PROFILE_NAME: ${{ secrets.AZURE_CERT_PROFILE_NAME }}
    if: ${{ needs.call-workflow-tarball.outputs.has_changes == 'true' }}

  call-workflow-abi:
    needs: [call-workflow-tarball, call-workflow-ctest]
    uses: ./.github/workflows/abi-report.yml
    with:
      file_ref: '4.3.0'
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      use_tag: snapshot
      use_environ: snapshots
    if: ${{ needs.call-workflow-tarball.outputs.has_changes == 'true' }}

  call-workflow-release:
    needs: [call-workflow-tarball, call-workflow-ctest, call-workflow-abi]
    permissions:
      contents: write # In order to allow tag creation
    uses: ./.github/workflows/release-files.yml
    with:
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      file_branch: ${{ needs.call-workflow-tarball.outputs.file_branch }}
      file_sha: ${{ needs.call-workflow-tarball.outputs.file_sha }}
      use_tag: snapshot
      use_environ: snapshots
    if: ${{ needs.call-workflow-tarball.outputs.has_changes == 'true' }}

  call-workflow-remove:
    needs: [get-old-names, call-workflow-tarball, call-workflow-ctest, call-workflow-abi, call-workflow-release]
    permissions:
      contents: write # In order to allow file deletion
    uses: ./.github/workflows/remove-files.yml
    with:
      file_base: ${{ needs.get-old-names.outputs.hdf4-name }}
      use_tag: snapshot
      use_environ: snapshots
    if: ${{ needs.call-workflow-tarball.outputs.has_changes == 'true' }}

