name: hdf4 dev CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '.github/CODEOWNERS'
    - 'doc/**'
    - 'release_docs/**'
    - 'COPYING'
    - '**.md'

# Using concurrency to cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.sha || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel. We just have one job, but the matrix items defined below will
# run in parallel.
jobs:
  workflow-autotools:
    name: "Autotools Workflows"
    uses: ./.github/workflows/autotools.yml
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

  workflow-cmake:
    name: "CMake Workflows"
    uses: ./.github/workflows/cmake.yml
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

#  workflow-msys2-autotools:
#    name: "CMake msys2 Workflows"
#    uses: ./.github/workflows/msys2-auto.yml
#    with:
#        build_mode: "production"
#        build_option: "--enable-production"

  workflow-msys2-cmake:
    name: "CMake msys2 Workflows"
    uses: ./.github/workflows/msys2-cmake.yml
    with:
        build_mode: "Release"
