name: arm64 OpenBSD 7.3 CMake

on: [push, pull_request]

jobs:
  test: # make sure the action works on a clean machine without building
    name: ${{ matrix.os.name }} ${{ matrix.os.architecture }} ${{ matrix.os.version }} on ${{ matrix.os.host }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: openbsd
            architecture: arm64
            version: '7.3'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.11.0
        env:
          FOO: A
          BAR: B        
        with:
          environment_variables: FOO BAR        
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash          
          run: |
            uname -a
            echo $SHELL
            pwd
            ls -lah
            whoami
            env | sort
            sudo pkg_add git
            git clone https://github.com/HDFGroup/hdf4
            cd hdf4
            sudo pkg_add cmake
            sudo pkg_add jpeg
            mkdir build
            cd build
            cmake -DHDF4_BUILD_FORTRAN:BOOL=OFF ..
            make
            make test
